import Mathlib

#eval 1 + 2
#eval 1 + 2 * 5
#eval String.append "Hello " "World"
#eval String.append "great " (String.append "oak " "tree")
#eval 42 + 19
#eval String.append "A" (String.append "B" "C")
#eval if 3 == 3 then 5 else 7
#eval if 3 == 4 then "equal" else "not equal"
#eval (1 - 2: Nat)
#eval (1 - 2: Int)
#check (1 - 2: Int)

-- #check String.append ["hello", ""] "world"
-- Returns an error
-- Application type mismatch: The argument
--  ["hello", ""]
-- has type
--  List String
-- but is expected to have type
--  String
-- in the application
--  String.append ["hello", ""]

def lean : String := "Lean"
-- This does not define a function that returns "Lean", but associates the
-- "variable" lean with the string "Lean"

-- To define a function, it's necessary to provide at least one argument
def add_one (n : Nat) : Nat := n + 1
-- Syntax: def (function name) (argument : type) : (return type) := (algorithm)
def maximum (n : Nat) (k : Nat) : Nat :=
  if n < k then
    k
  else n

-- Example
#eval maximum (5+8) (2 * 7)
-- maximum (5 + 8) (2 * 7) =>
-- maximum 13 14 =>
-- if 13 < 14 then 14 else 13 =>
-- 14 (returned value)

def spaceBetween (before : String) (after : String) : String :=
  String.append before (String.append " " after)

def joinStringWith (first : String) (second : String) (third : String) : String :=
  String.append second (String.append first third)

#eval joinStringWith ", " "one" "and another"

#check joinStringWith ": "
-- String -> String -> String

def volume (h : Nat) (w : Nat) (d : Nat) : Nat :=
  h * w * d

#eval volume 22 15 22

-- As functional programming is basically a type of lambda calculus,
-- there's no "two-argument functions": everything is treated as
-- a function that creates a function, and so on.
-- Let's do a math example: f(x) = 2x + 1 could be written as
-- g(x) = x + 1, h(x) = 2x => h(g(x)) = f(x)
-- Read: https://en.wikipedia.org/wiki/Lambda_calculus

-- There are two ways to define a type
def Str : Type := String
-- and
abbrev Str_Abr : Type := String

-- There is an error which occurs because Lean allows number literals to be overloaded.
-- When it makes sense to do so, natural number literals can be used for new types,
-- just as if those types were built in to the system.
-- This is useful because different branches of mathematics use number notation
-- for different purposes. (An example which I can think of is group theory, permutation groups.)
-- Behind the scenes, some definitions are internally marked as being unfoldable during overload
-- resolution,
-- while others are not.
-- Definitions that are to be unfolded are called reducible.

-- Sometimes to solve a particular problem it's helpful to create a struct (which is, in principle,
-- made with simpler types).
-- Structures are similar to structs in C and Rust, or records in C#.

-- Let's create two structures, one to represent points in R^2 using Cartesian coordinates and
-- another to represent
-- points using polar coordinates.
structure Cartesian_Point where
  x : Float
  y : Float

structure Polar_Point where
  r : ℝ
  θ : ℝ
  θ_nonneg : 0 ≤ θ
  θ_le_360 : θ ≤ 360


-- SYNTAX NOTES: := vs ← (<-) in Lean 4 (Generated by aristotle) (Note: Everything that has/will be
-- done with aristotle will be at the end of the file with credits.)
--
-- := (colon-equals) — PURE DEFINITION / BINDING
--   Used to bind a name to a value (not a computation). It appears in:
--
--   1. Top-level definitions:
--        def x := 5
--        def greet (name : String) : String := "Hello, " ++ name
--
--   2. let bindings (pure, no side effects):
--        let x := 2 + 3     -- x is just the value 5
--
--   3. Term-mode proofs:
--        theorem foo : 1 + 1 = 2 := rfl
--
--   The right-hand side of := is evaluated immediately and the result is
--   bound to the name on the left. There is no "unwrapping" happening.
--
--  ← or <- (left arrow) — MONADIC / EFFECTFUL BINDING
--
--   Used inside do blocks to extract a value from a monadic computation
--   (e.g. IO, Option, Except). It "unwraps" the result:
--
--     def main : IO Unit := do
--       let name ← IO.getStdin          -- IO.getStdin has type IO IO.FS.Stream
--                                        -- ← extracts the IO.FS.Stream from the IO
--       let line ← name.getLine          -- getLine has type IO String
--                                        -- ← extracts the String from the IO
--       IO.println s!"You said: {line}"
--
--   Compare with := inside a do block:
--
--     def example : IO Unit := do
--       let x := 2 + 3      -- pure binding, x : Nat (no unwrapping)
--       let s ← IO.getLine  -- monadic binding, s : String (unwrapped from IO String)
--       IO.println s!"{x} and {s}"
--
--   In summary:
--     let x := expr  →  x has the same type as expr
--     let x ← expr   →  expr has type M α for some monad M, and x has type α
--
-- In tactic mode, ← has a different meaning:
--   rw [← h]  means "rewrite using h in the reverse direction"
--   (i.e., if h : a = b, then rw [← h] rewrites b to a)
